Remove commas in setup.cfg package classifiers
This is likely causing an upload to pypi to fail with the following
error:

    Error: 'Development Status :: 3 - Alpha,' is not a valid choice for this field

Change-Id: Ieba2a4bec5ffc8e618501b38f73628e0b59c12a5
(cherry picked from commit b53f01d07d65e3b23da1870a0baca06067692616)